catalog/urls.py
from django.urls import path, include
from . import views

urlpatterns=[

    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('allloans/', views.LoanedBooksToLibrarianListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/'))

]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
import uuid

class Genre(models.Model):
    name=models.CharField(max_length=200, help_text="Enter a book genre(e.g. Science Fiction)")

    def __str__(self):
        return self.name

class Book(models.Model):
    title=models.CharField(max_length=200)

    author=models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary=models.TextField(max_length=1000, help_text='Enter a brief description of the book')

    isbn=models.CharField('ISBN',max_length=13, unique=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    genre=models.ManyToManyField(Genre, help_text='Select a genre for this book')

    language=models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    id=models.UUIDField(primary_key=True, default=uuid.uuid4(), help_text='Unique ID for this particular book across whole library')
    book=models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint=models.CharField(max_length=200)
    due_back=models.DateField(null=True, blank=True)
    borrower=models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)




    LOAN_STATUS=(
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status=models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability'
    )

    class Meta:
        ordering=['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),('can_see_all_loans', "See all the loaned books"))

    def __str__(self):
        return f'{self.id} {self.book.title}'

    def is_overdue(self):
        return bool(self.due_back and date.today() > self.due_back)

class Author(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    date_of_birth=models.DateField(null=True, blank=True)
    date_of_death=models.DateField('died', null=True, blank=True)

    class Meta:
        ordering=['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class Language(models.Model):
    name=models.CharField(max_length=100)

    class Meta:
        ordering=['name']

    def __str__(self):
        return f'{self.name}'

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import BookInstance


class RenewBookForm(forms.Form):
    renewal_date=forms.DateField(help_text="Enter a date between now and 4 weeks. (default 3)")

    def clean_renewal_date(self):
        data=self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))


        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))


        return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

catalog/views.py
import datetime

from django.shortcuts import render, get_object_or_404
from .models import Book, BookInstance, Author, Genre, Language
from django.contrib.auth.decorators import permission_required, login_required
from django.views import generic
from django.urls import reverse
from django.http import HttpResponseRedirect
from .forms import RenewBookForm


def index(request):
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.all().count()
    num_genres_fiction=Genre.objects.filter(name__icontains='fiction').count()
    num_genres=Genre.objects.all().count()
    num_books_harrypotter = Book.objects.filter(title__icontains='harry').count()

    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits']=num_visits+1
    context={
        'num_books':num_books,
        'num_instances':num_instances,
        'num_instances_available':num_instances_available,
        'num_authors':num_authors,
        'num_genres':num_genres,
        'num_genres_fiction':num_genres_fiction,
        'num_books_harrypotter':num_books_harrypotter,
        'num_visits':num_visits,
    }

    return render(request, 'index.html', context=context)

class AuthorListView(generic.ListView):
    model=Author
    paginate_by = 1
    context_object_name = 'author_list'
    queryset = Author.objects.all()[:5]
    template_name = 'authors/my_arbitrary_template_name_list.html'

    def get_queryset(self):
        return Author.objects.all()[:5]

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(AuthorListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context

class AuthorDetailView(generic.DetailView):
    model=Author

def author_detail_view(request, primary_key):
    author=get_object_or_404(Author, pk=primary_key)

    return render(request, 'catalog/author_detail.html', context={'author':author})


class BookListView(generic.ListView):
    model=Book
    paginate_by = 1
    context_object_name = 'book_list'
    queryset = Book.objects.all()[:5]
    template_name = 'books/my_arbitrary_template_name_list.html'

    def get_queryset(self):
        return Book.objects.all()[:5]

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context

class BookDetailView(generic.DetailView):
    model=Book

def book_detail_view(request, primary_key):
    book = get_object_or_404(Book, pk=primary_key)

    return render(request, 'catalog/book_detail.html', context={'book': book})

from django.contrib.auth.mixins import LoginRequiredMixin

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact='o')
            .order_by('due_back')
        )

class LoanedBooksToLibrarianListView(LoginRequiredMixin, generic.ListView):
    model=BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_to_librarian.html'
    paginate_by = 5
    permission_required='catalog.can_see_all_onloans'

    def get_queryset(self):
        return (
            BookInstance.objects.filter(status__exact='o').order_by('due_back')
        )

@login_required
@permission_required('catalog.can_mark_required')
def renew_book_librarian(request, pk):
    book_instance=get_object_or_404(BookInstance, pk=pk)

    if request.method=='POST':
        form=RenewBookForm(request.POST)

        if form.is_valid():
            book_instance.due_back=form.cleaned_data['renewal_date']

            book_instance.save()

            return HttpResponseRedirect(reverse('all-borrowed'))

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/06/2020'}

class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__' # Not recommended (potential security issue if more fields added)

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

class BookCreate(CreateView):
    model=Book
    fields=['title', 'author', 'summary', 'isbn', 'genre', 'language']

class BookUpdate(UpdateView):
    model=Book
    fields='__all__'
class BookDelete(DeleteView):
    model=Book
    success_url = reverse_lazy('books')

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html"%}

{% block content %}
    <h1 style="margin-top:20px;">Author: {{author.last_name}}, {{author.first_name}}</h1>

    <p>{{author.date_of_birth}} - {% if author.date_of_death == None%} {% else %}{{author.date_of_death}}{%endif%}</p>

    <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for book in author.book_set.all %}
        <hr>
        <a href="{{ book.get_absolute_url }}">{{book.title}}</a>
        <p> {{book.summary}} </p>
<!--      <hr>-->
<!--      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">-->
<!--        {{ copy.get_status_display }}-->
<!--      </p>-->
<!--      {% if copy.status != 'a' %}-->
<!--        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>-->
<!--      {% endif %}-->
<!--      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>-->
<!--      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>-->
    {% endfor %}
  </div>


{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 style="margin-top: 20px">Author List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{author.first_name}}</a> ({{author.date_of_birth}} - {% if author.date_of_death == None%} {% else %}{{author.date_of_death}}{%endif%})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no authors saved.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book.title }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>

      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 style="margin-top:20px;">Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p>{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_to_librarian.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }}) , borrowed by {{bookinst.borrower}}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}